name       : geany-plugins
version    : 1.38.0
release    : 19
source     :
    - https://github.com/geany/geany-plugins/archive/refs/tags/1.38.0.tar.gz : 86d2fe05290136d020b0d22f849a1aaa74b83cb49b767ae2dc19aaedcdf3d469
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
