name       : geany-plugins
version    : '1.33'
release    : 11
source     :
    - https://download.geany.org/geany-plugins/geany-plugins-1.33.tar.bz2 : 12825739e2c3caefbc1ad57e62f1e4f691af8db8368f173aa84c43dffb4503a2
license    :
    - GPL-2.0
    - GPL-3.0
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(check)  # check
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - cppcheck          # check
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
