name       : geany-plugins
version    : 1.31
release    : 7
source     :
    - https://download.geany.org/geany-plugins/geany-plugins-1.31.tar.bz2 : 76bd9e803db5a626b86669f08330cf95b8cc35057a1cdf65759bc00aef120e25
license    :
    - GPL-2.0
    - GPL-3.0
component  : editor
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(geany)
    - pkgconfig(libgit2)
    - pkgconfig(gtkspell-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
