name       : geany-plugins
version    : 1.32
release    : 10
source     :
    - https://download.geany.org/geany-plugins/geany-plugins-1.32.tar.bz2 : 78d4b394fe22fda298e80a22616421efdd4a419eb227b99eadca73f65abac117
license    :
    - GPL-2.0
    - GPL-3.0
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(check)  # check
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - cppcheck          # check
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
