name       : geany-plugins
version    : 1.27
release    : 2
source     :
    - http://plugins.geany.org/geany-plugins/geany-plugins-1.27.tar.gz : b8254fa6dfad5578d3b4e6bcb7ea227053fd7a8b6bacd65ecf4ca032ce07a6f6
license    :
    - GPL-2.0
    - GPL-3.0
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
component  : editor
builddeps  :
    - pkgconfig(geany)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
