name       : geany-plugins
version    : '1.36.0'
release    : 17
source     :
    - https://github.com/geany/geany-plugins/archive/1.36.0.tar.gz : 39409e948502a7d6d88a290f201b7c6c678ce8ecaff7c73589ee0f6dcc059568
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
