name       : geany-plugins
version    : 1.37.0
release    : 18
source     :
    - https://github.com/geany/geany-plugins/archive/refs/tags/1.37.0.tar.gz : 14df1dda3760eedd3a28daba0788f3bee5b83ae31f042c57a78c20f37a77eb28
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
