name       : geany-plugins
version    : 1.34
release    : 12
source     :
    - https://download.geany.org/geany-plugins/geany-plugins-1.34.tar.bz2 : 244417c681636e82a63cf6f9901b5b7f3889168f7d9b5ba9b45601767a589c3b
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(check)  # check
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - pkgconfig(webkit2gtk-4.0)
    - cppcheck          # check
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
