name       : geany-plugins
version    : 1.35.0
release    : 15
source     :
    - https://github.com/geany/geany-plugins/archive/1.35.0.tar.gz : 8a46ed8ed79443ec891e0ac2da039ece666de1601178afe030dd50bcd6515fce
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : editor
libsplit   : no
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
builddeps  :
    - pkgconfig(check)  # check
    - pkgconfig(geany)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2)
    - pkgconfig(webkit2gtk-4.0)
    - cppcheck          # check
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
