name       : geany-plugins
version    : 1.29
release    : 4
source     :
    - http://plugins.geany.org/geany-plugins/geany-plugins-1.29.tar.bz2 : 2827e0cf8f58a45759c82b690af5401dbd3ea0ec8dac310e4caea55547637bd7
license    :
    - GPL-2.0
    - GPL-3.0
summary    : The combined Geany Plugins collection
description: |
    The combined Geany Plugins collection
component  : editor
builddeps  :
    - pkgconfig(geany)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
